Why are civil conflicts sometimes contested by multiple rebel factions, while in other cases by a single, cohesive group? In a static sense, I argue that it is the choice of ideologies and identities around which rebellions mobilize that determines whether they incorporate most of the dissidents in a society, or whether many dissidents are left to form their own groups. These arrangements are often fragile, however, as factors such as government repression can lead dissidents to become more receptive to new bases of organization. Drawing on the literature reviewed in Chapter \@ref(introduction), I identify three processes through which these individual dynamics shape the number of rebel groups in a civil war. First, entirely new groups can enter the conflict. Second, previously cohesive groups can splinter into multiple successor organizations. Finally, previously independent groups sometimes merge. In the remainder of this chapter I articulate a set of assumptions, a theory of the internal politics of dissident movements, and a set of hypotheses to be tested in subsequent chapters.

## The Formation of Rebel Groups

I argue that rebellions tend to emerge out of similar processes. In any state there will naturally be some portion of the populations that either publicly or secretly opposes the regime, which I call the "dissident pool." Entrepreneurial individuals attempt to construct rebel groups from this pool. They do so by making appeals centered around ideals or identities that they expect will attract a sufficient number of followers, with appeals that mobilize existing organizations being especially attractive. While rebel groups tend not to be especially democratic once forming, the ability of members to exit the group creates a degree of accountability. When rebel leaders fail to accommodate the changing demands of their members, realignments should often ensue.

### The Dissident Pool

I start from the assumption that rebel groups are drawn from a broader pool of dissidents. By dissident, I mean an individual who opposes the government. Dissidents are grouped into a variety of potentially overlapping organizations. Some may belong to non-violent political organizations such as trade unions or political parties. Others may use violence as members of a rebel group. Hereafter I refer to the complete set of rebel groups as the rebel movement. In some cases this rebel movement will consist of a single group, if there is only one rebel organization associated with the dissident pool. In the American Civil War, for example, the dissidents were represented by a single Confederate Army, though even in this case there were several militias with only a loose attachment to the main rebel group. In other cases the rebel movement may contain several distinct rebel groups, such as the Shan State conflict in Burma, which has produced at least six rebel groups.

At the individual level, dissidents are likely to vary on several dimensions. First, individuals differ in their level of involvement in violence. @Lichbach1995 [17] identifies five gradations of participation which range from being constituents who may not even consent to being represented by the dissident movement, to activists who engage in political activity but not necessarily violence, to militants who participate in violence or work in close support of such efforts. For instance, civilian activists may provide crucial material and logistical support to rebels [see @Weinstein2007; @Parkinson2013c]. Relatedly, dissidents may utilize different "repertoires of contention" [@Tilly1986; @Tilly2006], perhaps reflecting the resources and past behavior of the groups through which they are mobilized. For example, some elements of the dissident pool might specialize in non-violent actions such as boycott, others on conventional political channels such as elections, and still others in engage in violence. In addition to varying across individuals, the willingness to use violence is often dynamic --- previously violent individuals often desert their rebel group, and previously non-violent individuals can be moved to participate in the fighting.

Social identities form a second dimension of variation among dissidents. A few dissident movements are exceptionally homogenous. For example, some separatist movements benefit from a coincidence of ethnicity, language, religion, and geographic location. In most cases, however, there is some amount of diversity along these attributes. For example, the Kurds share a common ethnicity and language, but practice a variety of faiths. Bids to overthrow the central government might be made by coalitions featuring representatives of multiple ethnic groups, religions, languages, and regions. Rebel leaders often emphasize broad, inclusive goals and identities, hoping to gain the support of a large portion of society. Such coalitions are often vulnerable to "outbidding appeals" [@Rabushka1972; @horowitz85], through which moderate, diverse groups lose support to competitors claiming to explicitly represent a particular identity group.

Finally, while dissidents share a common interest in removing the incumbent government, they do not necessarily agree on many other political questions. Rural dissidents might make land reform their top priority in a post-war government, whereas urban dissidents might care more about welfare or modernization programs. Some dissidents hope to take control of a government with strong centralized authority, while others hope to procure greater regional autonomy as a consequence of the war. Broader left-right ideological divisions are often present, and doctrinal differences often divide groups with relatively similar views. For example, Indian communists were long divided into Maoist and Marxist-Leninist factions. Even when dissidents largely agree on goals, there are likely to be divisions between hardliners and moderates, who will be more willing to accept compromises and less willing to adopt extreme tactics. Finally, even dissidents who largely agree on questions of policy will still find themselves in competition over the power and private benefits of government [@Christia2012], which are subject to rival consumption.

In short, the pool of individuals who oppose the government often form a mix of violent and non-violent organizations, and tend to have several social and political cleavages that might serve as the basis for organizational fragmentation. I argue that whether such divisions do produce fragmented groups, however, is contingent on contextual factors which I explore in the following section.

#### Changes to the Dissident Pool

I generally treat the dissident pool as a fixed set of government opponents. In reality, however, it will often change in size over the course of the conflict. Throughout history civilians have often fled conflict to become refugees. While one might reason that dissidents are somewhat less likely to do this than neutral civilians, in many conflicts the dissident pool is undoubtedly depleted by fleeing members. Successful counterinsurgency operations by the government or third parties can also reduce the ranks of the dissidents. Both rebels and non-violent dissidents are often killed in great numbers, and even when they are not, they may be subjected to imprisonment or repression that makes mobilization difficult. Under certain conditions, dissidents may even defect to the government side [@Staniland2012d].

In other cases the dissident pool may grow. Government repression may induce previously neutral civilians to support the opposition. Dissidents may attract support by offering a morally or politically superior platform to the government's, or by obtaining legitimacy through their choice of tactics or international support [@Chenoweth2011]. Rebels may attract new supporters by demonstrating strength and by extension their prospects for success [@Christia2012], or by offering private benefits to recruits [@Weinstein2007]. Rebel groups may also attract or coerce support from civilians by controlling territory [@Mampilly2011]. Finally, dissidents may be bolstered by international support. The Islamic State has recruited young Muslims from around the world to join them in Syria. At a less violent level, the Liberation Tigers of Tamil Eelam enjoyed significant financial support from the Tamil diaspora, effectively giving them a larger civilian support network than they had locally.

While I am primarily interested in changes to the structure of the dissident movement independent of its size, it is important to consider the possibility that the dissident pool may change in composition as well.

### Entrepreneurs and Rebel Mobilization

One school of thought in the literature on the causes of civil war argues that rebellion is motivated primarily by the pursuit of private benefits such as oil rents or profits from illicit trades [@mueller00; @Collier2004]. This so-called "greed hypothesis" implies that rebels are not necessarily insistent upon defeating the government. While doing so may be desirable in some cases if control of the state brings significant revenue streams, often rebels aspire only to preserve their control of revenue from sources such as drug cultivation. @Kalyvas2006 similarly believes that rebel violence is often motivated by private concerns, though he sees personal rivalries as a more common priority than material wealth.

I depart from the greed school and follow @Lichbach1995 and @Weinstein2007 in viewing private benefits such as drug revenues as a recruiting tool and secondary benefit of rebellion, rather than an end in themselves. The ultimate goal of rebel groups, then, are political outcomes such as the overthrow of the central government, or autonomy for a particular region. Thus, all else equal, rebel groups should prefer to defeat the government militarily. Short of that, they should prefer to use gains on the battlefield to secure at least a portion of their political goals in a postwar peace agreement. This creates an incentive for rebel leaders to amass as much military and political power as possible. Yet, even as a secondary motive, private benefits create a countervailing incentive to limit the size of one's group, so as to maximize the share of benefits distributed to each member. Ultimately, then, rebels should seek to build minimum winning coalitions just strong enough to win the war [@Christia2012].

I conceptualize rebellion as emerging from the efforts of entrepreneurial individuals, who seek to recruit fellow dissidents to participate in violence. There are several challenges inherent to such a task. First, persuading individuals to participate in collective action is generally difficult, and especially so in the high-risk context of rebellion. Second, rebellions generally need to build capacity quickly, to ensure that they can survive government repression. Indeed, @Lewis2016a finds that many rebel groups fail within a few months. Third, achieving political goals typically requires a cohesive rebel group that is able to avoid infighting and splintering [@Staniland2014]. Finally, rebel entrepreneurs should prefer to organize groups on a basis that allows them to exclude some segments of the population from receiving private benefits [@Christia2012].

I expect that drawing on existing organizations such as political parties, religious organizations, student groups, or labor unions will solve many of these problems. Social networks can often solve collective action problems by sanctioning individuals who decline to participate [@Marwell1988]. Many civil society organizations will produce such ties among members. Drawing from existing groups also offers the possibility of mobilizing a large number of people quickly, particularly if rebel entrepreneurs can gain the support of group leadership. Existing social organizations can also produce a cohesive rebel group, particularly if they have strong vertical ties between leadership and rank-and-file members, and strong horizontal ties between chapters or geographic areas [@Staniland2014]. Finally, building a movement by recruiting existing groups will often allow rebel entrepreneurs some control over group size, whereas recruiting individuals may not.

Consistent with these notions, my own data collection shows that most rebel groups can trace their origins to a pre-existing organization such as a political party, militia, or student organization [see also @Staniland2014]. Comparatively few have emerged through grassroots processes, such as protesters steadily becoming more violent and organized (see Figure \@ref(fig:origins)).

```{r origins, echo=F, message=F, cache=T, fig.cap="The Origins of Rebel Groups, 1946--2015"}
library(ggplot2)
library(dplyr)

origins = read.csv("rebel_origins_clean.csv")

origins$origin <- recode(origins$origin, "protests"="Protests", "grassroots"="Protests", "political party"="Political Organization", "student organization"="Student Organization", "alliance - political parties"="Political Organization", "underground resistance"="Political Organization", "secessionist organization"="Political Organization", "occupying military"="Regime Military Faction", "deposed government"="Civilian Government", "exiles/diaspora"="Civilian Government", "government faction"="Civilian Government", "regional government"="Civilian Government", "criminal organization"="Economic Organization", "economic organization"="Economic Organization", "mercenaries"="Militia", "transnational militant organization"="Transnational Organization", "transnational political organization"="Transnational Organization", "foreign intervention"="Foreign Sponsorship", "remnant"="Split from Existing Rebel Group", "anti-colonial"="Political Organization", "alliance; religious"="Alliance of Existing Groups", "political party; anti-colonial"="Political Organization", "civilian.gov"="Civilian Government", "transnational political organization; alliance"="Transnational Organization", "religious organization; foreign intervention"="Religious Organization", "anti-colonial; regional government"="Political Organization", "student organization; tribal groups"="Student Organization", "militia; military faction"="Militia", "military faction; splinter"="Regime Military Faction", "exiles/diaspora; foreign intervention"="Foreign Sponsorship", "military faction; foreign intervention"="Regime Military Faction", "political party; military faction"="Political Organization", "military faction; transnational militant group; exiles/diaspora"="Regime Military Faction", "splinter"="Split from Existing Rebel Group", "military faction"="Regime Military Faction")

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}
origins$origin <- sapply(as.character(origins$origin), simpleCap)

origins <- origins  %>%
 group_by(origin) %>%
 mutate(count=n())

origins <- transform(origins, origin=reorder(origin, -count))

ggplot(origins, aes(x=origin)) + geom_bar() + theme_bw() + ylab("Count") + xlab("Origin") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

The implication of this argument is that initially, at least, the structure of rebel movements will reflect the structure of pre-war civil society. If a single organization connects most or all dissidents in a country, it may be possible for dissidents to build a unified group on that basis. For instance in a two-party system most regime opponents might share common membership in the opposition party. When no such unifying organization exists, the probability that multiple rebel groups will emerge is much higher. This argument also implies that the choice of basis on which entrepreneurs attempt to organize rebellions will be endogenous to the degree of prior organization around said bases. For example, in much of the Middle East freedom of assembly is granted only to religious organizations, meaning that religious identity is likely to form the basis of rebellions there, while ideological or occupational identities are unlikely to do so.

## Repression and the Dynamics of Individual Attitudes

While the availability of existing organizations plays a large role in determining which ideologies and identities rebel entrepreneurs initially employ in recruiting members, the appeal of these bases of mobilization can change over time. I am particularly interested in changes in the extent to which individual dissidents orient towards sub-national identities such as ethnicity or religion,^[Subsequently, I focus primarily on ethnicity. I expect that ethnicity will be the most salient cleavage in a majority of societies, but in some cases religion or other identities may play this role.] which often provide a basis for division within the dissident movement, and more inclusive priorities such as a non-sectarian ideology. I expect that government repression will be a crucial determinant of this orientation.

### The Relative Cost of Fighting

One dissident attribute that can be altered by repression is the willingness to engage in violence. The willingness to participate in rebellion is largely a function of demographic traits, with impoverished young men accounting for a large portion of recruits [@Humphreys2008]. The role of poverty is thought to be related to opportunity costs - individuals with comfortable lifestyles are unlikely to take on the risks of fighting, while impoverished individuals have little to lose [@Collier2004]. The cost of participating in rebellion relative to non-violence is not necessarily static, however. Indiscriminate violence against civilians can reduce the the risk of participation in violence relative to that of non-violence, by making non-violence more dangerous and thus less desirable [@Kalyvas2007]. If the physical risk of remaining peaceful is not dramatically lower than that of fighting, the cost of participating in rebellion is relatively low.

Thus, individuals who experience repression, either personally or in close enough proximity to influence their expectations of safety, should become more willing to engage in violence. Individual thresholds for violence will continue to vary, meaning that some will continue to remain peaceful. Yet in general, the number of dissidents who are willing to engage in violence should increase with the risk of physical harm from repression.

### Ethnic Identity

Some theoretical perspectives view ethnic and other social identities as largely immutable, having been the basis for conflict across many generations, and perhaps even deriving from a biological basis [@horowitz85]. Increasingly, however, scholars view identity as a product of individual or collective choice. @Posner2005 argues that individuals choose to prioritize one of several identities such as ethnicity, language, religion, or class, selecting that which is likely to bring them the greatest benefit. Focusing on the realm of electoral politics, he finds that this choice is shaped by an interaction between group size and electoral institutions. In subsequent work @Eifert2010 find that individuals are more likely to identify with their ethnic group when interviewed near a competitive election, suggesting that ethnicity is deployed instrumentally during elections. @Penn2008 models a similar calculation in which individuals choose to orient themselves toward a national or ethnic identity. She finds that ethnic identities become more prevalent as ethnic groups become homogenous, and as economic inequality between ethnic groups increases. @Christia2012 extends the argument to civil wars, arguing that ethnic identities are deployed instrumentally, with rebel elites emphasizing particular identities to justify alignments that are in fact driven by power politics. A key consequence of this malleability of identity is that ethnic outbidding is not inevitable - if political actors can appeal to multiple, overlapping identities, competition is no longer zero-sum [@Chandra2005]. The opposite is also true, however - previously cooperative relationships can be undermined by enhancing the salience of ethnic identities.

I argue that violent repression should tend to increase the extent to which individuals identify with their ethnic group.^[Hereafter I will refer mainly to ethnicity as the primary alternative to broad identities. In some societies other social markers such as religion are likely to be more salient, but I expect these to operate in a similar manner to ethnicity.] A vast scholarly literature views ethnic identity as a cause of conflict [e.g. @horowitz85]. Several scholars have considered the possibility of a causal relationship running in the opposite direction, with conflict influencing individual identity. The bulk of this work argues that external threats such as interstate war can promote the creation of national identities, facilitating statebuilding [@Herbst1990; @Tilly1992; @Gibler2012]. @Gibler2012 focus on territorial threat as the key driver of identity changes. As many territorial disputes are driven by irredentist logics (i.e. a state seeks to acquire territory that is home to ethnic groups prevalent within its own borders), citizens in the target state have a strong incentive to emphasize national identities to avoid the impression that they support the challenging state. @Herbst1990 [122] similarly sees interstate war as a crucial source of nationalism, arguing that "...people realize in a profound manner that they are under threat because of who they are as a nation; they are forced to recognize that it is only as a nation that they can successfully defeat the threat."

Others have speculated that an opposite process may occur in civil wars, whereby individuals become more oriented toward ethnic identities. @Kaufmann1996 argues that in conflicts where ethnicity is the primary dividing line, individuals will experience a security dilemma in which their survival is increasingly tied to the success of their group. However, this does not explain why ethnicity would become the basis for conflict in the first place. @Kuran1998 offers an explanation for this, arguing that "ethnic activists" can provoke a cascade of increased ethnic identification, particularly when they use violence on behalf of the ethnic group. He explains,

>"Ethnic violence, along with the ensuing reactions, repression, and counter-violence, creates ethnic grievances, and it revives memories of past sufferings. Often, therefore, it makes people of all ethnic groups turn inward as a precaution against further violence," [@Kuran1998, 46].

Often repression is applied in a manner with the potential to highlight ethnic identities. Distinguishing dissidents from pro-government or neutral individuals is generally quite difficult [@Kalyvas2006]. If detailed knowledge about particular individuals is unavailable, governments may adopt crude solutions to this problem, assuming that particular social groups or locales are generally sympathetic to the opposition. Repression of this kind is likely to make ethnicity more salient, and trigger the linked fate mechanism described by @Kuran1998. If individuals are targeted for repression on the basis of their ethnicity, banding together with co-ethnics may offer their best chance at survival.

Individuals who participate in a rebel group are likely to be targeted by repression (or worse) regardless of whether it is applied on the basis of ethnicity or not. Thus, the preceding discussion applies most directly to non-violent dissident constituents. Yet, this increased ethnic identification among constituents can extend to rebel groups through two mechanisms. First, these individuals can demand a rebel group that represents them on more explicitly ethnic terms. This might be especially likely if dissidents feel that existing rebel groups have failed to adequately protect them from the government. As I discuss in more detail in the section below on "Joining," repression can lead previously non-violent individuals to take up arms, in some cases leading to the direct creation of new rebel groups. Second, rebels themselves may begin to identify more strongly with their ethnic group through their connections with family and friends who experience repression. As members see their own communities come under threat, they are likely to become less supportive of broad or abstract goals, and more supportive of efforts to defend particular groups or locales. As discussed in the section on "Splintering" below, these members may break away to form a new rebel group that places greater emphasis on ethnicity. They may also use the threat of doing so to induce existing groups to embrace ethnic identities.

### Government Agency

Thus far, I have treated repression as an exogenous influence on dissidents. In reality, the government is almost certainly a strategic actor, with its use of repression being endogenous to its expectation of how dissidents will respond. Governments might be more inclined to repress if they expect that doing so will sow division among their opponents. Alternatively, dissident pools that are already divided might be more attractive targets for repression than unified ones. It is important to account for such possibilities both theoretically and empirically. This is would be particularly true if my expectation that repression often produces fragmentation among dissidents is borne out, as it is not entirely clear whether this would be a desirable outcome for the government. Furthermore, if repression does in fact increase the number dissidents willing to resort violence, its use by governments becomes downright puzzling.

One explanation is that influencing the size or structure of rebel groups is not the only, and perhaps not even the primary purpose of repression in most cases. First, the governmental institutions involved in fighting rebels may differ from those that conduct the bulk of repression. Whereas civil wars tend to be conducted by state militaries, repression is often conducted by police forces or outsourced to pro-government militias, with less-than-perfect coordination between the entities [@Mitchell2014]. Second, rebellion is not always a particularly grave threat to a government's survival. Indeed, only about 16% of rebel groups defeat the government [@Cunningham2009]. By contrast, leaders routinely lose power through elections, and are sometimes forced to resign in the face of mass uprisings. If governments use repression to maximize their chances at political survival, deterring dissidents from voting or protesting may take priority over preventing or dividing rebel movements. In either case, the government's strategy of repression would not be (entirely) endogenous to its affect on rebel structure.

In some cases, however, repression is likely aimed at least partially at making rebellion more difficult. If, as I predict, repression reduces the cost of fighting and increases the willingness of its targets to participate in violence, the government's use of this tactic remains a puzzle. One explanation is a sort of gamble. At its most successful, repression might induce dissidents to flee the country and become refugees, deter violent mobilization by signaling resolve [@Pierskalla2010], or physically prevent collective action from occurring. The possibility of such a desirable outcome might lead governments to repress, even if doing so brings some risk of an escalating cycle of repression and increasingly violent dissent. As governments likely have incomplete information about their own ability to identify and repress dissidents, and about dissident resolve, counterproductive uses of repression are conceivable.

A more complete consideration of the government's use of repression is beyond the scope of this project. As the preceding section demonstrates, there are a number of theoretical accounts in which the structure of the dissident movement is incidental to the decision to repress. I provide further support for this notion with a variety of causal inference techniques in the subsequent empirical chapters.

### Non-Governmental Sources of Repression

To this point I have generally assumed that the government is the primary source of repression. In reality, this is not always true. Both rebels and their constituents may face violence from other rebel groups, outside states, or less political non-state actors such as militias or criminal organizations. In general I do not expect that the source of repression makes much difference for the process described above. If the risk of violence from any source increases, an individual's relative cost of participating in rebellion should decrease. As is the case with governments, some rebel groups and militias are clearly associated with particular ethnic groups and/or choose their targets for victimization on the basis of ethnicity. Repression in these cases should tend to increase ethnic identification, just as it would if it were applied by the government.

### Testing the Microfoundations

The preceding account includes several testable propositions about individual-level attitudes, which I evaluate in Chapter \@ref(survey-chapter). First, I follow @Kalyvas2007 in arguing that violent repression should reduce the relative cost of participation in violence. This implies that individuals who have personally been repressed^[The survey data I use (the Afrobarometer survey) only asks individuals whether they have been attacked, without specifying the attacking party.] should on average exhibit a greater willingness to engage in violence than individuals who lack such experiences.

*Hypothesis 1: Individuals who experience repression should be more willing to participate in political violence themselves*

Additionally, I expect that repression will tend to induce its targets to identify more strongly with their ethnic group^[In some cases a group type other than ethnicity, such as religion or clan might be more salient than ethnicity. However, my survey data asks only about ethnic identification.], as repression is often applied disproportionately to certain groups, increasing the salience of such identities.

*Hypothesis 2: Repression should increase the extent to which an individual identifies with their ethnic group*

## Processes of Structural Change

These individual-level dynamics produce changes in the overarching structure of the rebel movement through three processes. First, they can drive the formation of entirely new rebel groups. Second, they can lead individuals who already belong to a rebel group to break away into splinter organizations. Finally, they can facilitate the creation of alliances among previously independent groups.

### Joining

By "joining" I mean the entry of entirely new groups to the conflict. I define a group as new if it did not originate within another rebel group. A rebel group that draws its leadership and members from a political party that did not previously engage in violence would constitute a new group. I would consider a faction of an existing rebel group that breaks away to form its own organization to be a splinter organization, discussed in the following section. At a minimum, joining requires that two conditions be met. First, previously non-violent individuals must change their mobilizational calculus. This entails either participation in violence becoming more attractive, or remaining non-violent becoming less attractive.

Second, there must be a division among the dissident constituents. In other words, newly mobilizing individuals must have a reason for forming a new group rather than joining an existing one. At their most benign, these divisions might simply reflect the difficulty of coordinating actions across physical distance or linguistic barriers. For example, dissidents on opposite sides of a mountain range might choose to form independent organizations. In such cases the formation of multiple rebel groups might be a matter of convenience rather than an indicator of animosity or divergent objectives. In other cases, however, divisions may be deeper and more difficult to reconcile. For instance, if some rebels make improving the status of their ethnic group a primary concern, it is unlikely that members of other ethnic groups will join their organization, and any existing members with differing ethnic identities will be likely to leave.

As noted in the preceding discussion of individual-level dynamics, repression can satisfy both of these conditions. The application to the first condition requires little explanation. If, as I argue, repression reduces the relative cost of fighting, the pool of previously non-violent individuals suddenly willing to join the conflict should grow with the proportion of the dissident pool that is targeted. The crucial question, then, is whether they join existing rebel groups, or form new ones. I argue that in addition to changing the cost of fighting, repression should make individuals more inclined to emphasize sub-national identities such as ethnicity. How this translates to division at the rebel group level requires a discussion of the manner in which ethnicity shapes politics.

Intra-ethnic politics often follows a dynamic known as "outbidding," in which leaders make progressively more extreme proposals in hopes of winning the support of the group [@Rabushka1972; @horowitz85]. Key to these models are the assumptions that individuals identify with a single ethnic group, that they care only about ethnic issues, and that ethnic politics is a zero-sum game. This produces a completely polarized bargaining space in which individuals choose ideal points at which their group's interests are represented fully (e.g. a preference for a legislature in which group members hold a majority). In a spatial model of voting with such  parameters, the optimal strategy for politicians is to adopt the most extreme position possible [@Rabushka1972]. Even if a multi-ethnic coalition forms initially by creating uncertainty as to which group will be advantaged, it will eventually be undercut by challengers making more extreme appeals to a single ethnic group. Other bases of mobilization, by contrast, tend to produce more heterogeneous preferences - some members will actually prefer moderate positions - and thus greater potential for compromise. While the original formulation of the outbidding model assumes competition in an electoral context, it has also been shown to more violent forms of competition such as terrorism [@Kydd2006; @Chenoweth2010; but see @Findley2012a]. Thus as individual dissidents become more oriented toward ethnic identities, we should expect their willingness to participate in multi-ethnic coalitions to decrease. Rebel entrepreneurs should seize on this shift in preferences, and attempt to outbid existing rebel groups by forming rebel groups that place a greater emphasis on ethnic identity.

While this process should initially re-orient a subset of dissidents around the ethnic identities that are targeted with repression, the mobilization of one group can lead to similar behavior in others, even if the latter groups do not experience repression themselves. @Kuran1998 shows that ethnic identification is interdependent, meaning that if some members of society begin to emphasize ethnic identity more strongly, the probability that others will do so increases as ethnicity becomes more salient. Increased mobilization around one ethnicity can also pose a threat to members of other ethnic groups, leading them to mobilize as well [@Posen1993]. Perhaps for these reasons, several studies have found that contagion effects frequently cause a proliferation of both secessionist movements [@Ayres2000] and ethnic conflict [@Lane2016].

From this argument I derive three testable hypotheses. First, the probability of new groups joining a conflict should be highest when the level of repression in a country is highest.

*Hypothesis 3: The probability of new groups joining a conflict should increase with the level of repression in the country*

Second, the ability of repression to create new rebel groups should be moderated by the number of ethnic identities available for mobilization. If a country has high levels of repression, but low ethnic diversity, we should not expect the mechanism elaborated above to produce new rebel groups. This effect should be captured by an interaction between repression and ethnic diversity. I expect that when ethnic diversity is low, the effect of repression on the probability of joining should be low, as there are few ethnic groups available for activation. When diversity is high, however, the effect of repression should be large.

*Hypothesis 4: There should be a positive interaction between repression and ethnic diversity*

Finally, if the mechanism through which repression produces new rebels is in fact the activation of ethnic identities, we should expect to see this reflected in the characteristics of the joining rebel groups. Specifically, the joining groups should be especially likely to draw their support from a single ethnic group.

*Hypothesis 5: Rebel groups that join ongoing conflicts should be more likely than others to draw their support from a single ethnic group*

### Splintering

I define a splinter organization as a rebel group that was previously incorporated in a larger rebel group. Thus, whereas joining is a phenomenon driven by dissidents who did not previously engage in violence, splintering is driven by individuals who already belong to rebel groups. While rebels are generally more likely than constituents to experience violence, they are likely to be targeted for being militants, rather than for belonging to particular ethnic group. Thus, violence will often not have a direct effect on the identity of rebel group members. Yet, rebels and especially rebel entrepreneurs should respond to changes in the preferences of dissident constituents.

As discussed above, the leaders of a successful rebellion are likely to accrue a variety of private benefits. They will typically exert substantial control over post-war political and policy outcomes, and may have opportunities to skim profits from the state. Even before the war ends, rebel leaders often enrich themselves through the control of natural resources or illicit trades [@Collier2004]. Thus, enterprising dissidents should look for opportunities to gain control of their own rebel group.

Shifts in the identities of dissident constituents might offer such an opportunity. Civilian support networks can be a key source of material resources and logistical support for rebel groups [@Weinstein2007; @Parkinson2013c]. If a new rebel faction could win over a substantial number of dissident constituents, their chances of building a competitive organization would be substantially greater than they would in the absence of such resources. A shift among dissidents toward greater ethnic identification creates the possibility that a new group could win their support through an outbidding appeal, as discussed above. Civilians who are facing violence are quite likely to prefer a rebel group that can offer protection. If these civilians increasingly see the conflict in ethnic terms, a rebel group making an explicit claim to represent their ethnic group is likely to be more credible than groups lacking such a connection. Thus, rebels who see members of their ethnic group being repressed should have an incentive to break away from their existing organization and create a more explicitly ethnic splinter organization.

Similar to joining, I expect that repression will induce greater ethnic identification among dissident constituents, ultimately leading to an increased probability of splintering.

*Hypothesis 6: The probability that rebels groups splinter should increase with the level of repression in a country*

The mechanism proposed above assumes that pre-existing rebel groups are vulnerable to outbidding appeals because they are either multi-ethnic, or organized on a basis that does not emphasize ethnicity. If the original rebel group is strongly associated with a single ethnicity, however, it should be less likely to experience splintering.

*Hypothesis 7: Multi-ethnic rebel groups should be at greater risk of splintering than monoethnic ones*

Finally, this theory implies that splintering is done to create more explicitly ethnic rebel groups. Thus, I expect that splinter organizations should be more likely than groups that form though other means to be associated with a single ethnic group.

*Hypothesis 8: Splinter organizations should be more likely than others to draw their support from a single ethnic group*


### Alliance Formation

Both joining and splintering can increase the number of rebel groups active in a conflict. This number can decrease, however, when rebel groups form alliances. I define an alliance as substantial integration of capabilities and command by two or more previously active, independent rebel groups. Typically these alliances will result in the creation of a named umbrella organization to coordinate battlefield operations. For example, the Syrian Democratic Forces coordinates the actions of several Kurdish and Arabic forces in their fight against the Islamic State. Note that this definition entails a deeper level of integration than most alliances between states. I choose to focus on this category for two reasons. First, named umbrella organizations are easily identifiable, whereas less comprehensive cooperative arrangements are often not well-publicized, as rebels lack formalized processes such as treaties for creating them, and may have incentives to hide such cooperation from the government. Second, mergers of this sort have a meaningful effect on the complexity of civil wars, as rebel groups often channel most or all of their activities through umbrella groups. Less formal alliances, by contrast, are often short-lived, and may entail a more circumscribed form of cooperation, such as a non-aggression pact.

Rebel alliances can be valuable for a number of reasons. First, alliances aggregate capabilities. This is perhaps the most common conception of alliances in international politics [see @Bennett1997], and it has been proposed as a motive for rebel alliances as well [@Bapat2012; @Horowitz2013]. The logic of capability aggregation differs somewhat between international and civil conflicts. Whereas international alliances aggregate capabilities by bringing states into a conflict in which they might not otherwise participate, rebel groups by definition are already participating in conflict. Nevertheless, these alliances can bring great value because rather than simply aggregating, they can concentrate capabilities in space and time. For example, two rebel groups might be unable to capture a government-held town on their own, but in a joint operation would be sufficiently powerful to do so.

Second, alliances can allow for burden-sharing and specialization. Burden-sharing has been offered as an explanation for international alliances such as NATO [@Sandler1980], though it may not occur under all circumstances [see @Olson1966]. Alliances can ensure that a single rebel group is not responsible for defeating the government, and might serve as a mechanism for reigning in the temptation to free ride off of another group's efforts. Relatedly, alliances can facilitate specialization by rebel groups. For instance, one alliance partner might specialize in holding territory, while another specializes in launching offensives in new areas. Furthermore, they can share strategies and technical information. For example, Hamas is believed to have learned how to use suicide bombings through its alliance with Hezbollah [@Horowitz2013].

Third, alliances can manage conflict between members and ensure that their resources are directed toward common enemies. @Weitsman1997 argues that alliances often serve to tether powerful states to one another, so as to reduce the probability of conflict between them. @Gibler1996 finds that alliance treaties are often used to settle territorial disputes between the signatories. Similar alliances can be seen in civil wars, for example as a number of Syrian rebel groups agreed to focus their efforts in different regions of the country. This allows rebels to avoid conflict with each other. Compliance with such agreements is incentivized by the fact that reneging on the territorial arrangement would likely result in the loss of the other benefits of the alliance, such as capability aggregation.

Fourth, operating as an alliance bloc may be beneficial to the members groups in bargaining situations. An alliance with a set of coordinated demands might command greater bargaining leverage than individual members, who collectively have similar power, but a more disparate set of demands. Perhaps more crucially, alliances might mitigate credible commitment problems. Peaceful settlements to conflicts can be derailed by concerns that the other side will not adhere to the agreement [@fearon95]. In civil wars, this is often borne out by extreme "spoiler" factions. A rebel commitment to a peace agreement is more likely to be viewed as credible if it has formal control over other factions.

While the benefits are often many, most alliances between rebel groups are not without cost. The post-war political outcome, whether it comes in the form of a rebel victory or a compromise with the incumbent government, is likely to be shaped by all factions within the winning coalition. Thus, allying with another group holding differing ideologies and interests will tend to force a rebel faction to compromise on at least some issues, or to de-emphasize certain priorities. If, as I assume, rebels are motivated by political goals, the value of an alliance will decrease as its ideological similarity to its alliance partners decreases [@Bapat2012]. Furthermore, any private benefits deriving from the conflict outcome (such as seats in a post-war legistlature) must be divided among the members of the winning alliance [@Christia2012]. These concerns should tend to constrain the value of alliances in civil war. The existing literature finds that these concerns limit the size of rebel coalitions [@Christia2012]. Logically, they should also shape the choice of partners with whom rebels ally.

I do not expect that repression will systematically affect the willingness of rebel groups to form alliances in general. I do, however, expect that this process will influence the choice of alliance partners. As the level of threat to civilian constituents increases, the desire of co-ethnic rebels to provide protection should increase. As rebel coalitions grow broader and more diverse, the likelihood that they would prioritize the protection of any particular group should generally decrease. Rebel leaders attempting to stave off outbidding appeals, or initiate one themselves, should generally be disinclined to enter into multi-ethnic alliances under these conditions.

*Hypothesis 9: The probability that new, multi-ethnic alliances will form should decrease with the level of repression*

At the same time, increased ethnic identification might create opportunities for new alliances among rebel groups who share a common ethnicity. When the salience of ethnicity increases, differences on other social dimensions should decline in relative importance. For example, if two Kurdish rebel groups were previously unwilling to cooperate due to religious differences, an increase in the salience of ethnicity might paper over these differences, reducing the barriers to an alliance that would be otherwise desirable. Thus, in addition to making multi-ethnic alliances less likely, repression should increase the likelihood that mono-ethnic alliances will form.

*Hypothesis 10: The probability that new, mono-ethnic alliances will form should increase with the level of repression*

I provide comprehensive tests of these hypotheses in the following four chapters.
