---
title: "Politics Among Rebels: The Causes of Division Among Dissidents"
author: "David F. Bowden"
date: "`r paste(format(Sys.time(), '%B'), ' ', as.numeric(format(Sys.time(), '%d')), ',', ' ', format(Sys.time(), '%Y'), sep='')`"
output:
    bookdown::pdf_book:
        includes:
            in_header: preamble.tex
documentclass: book
bibliography: /Users/david/Dropbox/library.bib
biblio-sytle: apsr
link-citations: yes
fontsize: 12pt
fontfamily: tgpagella
geometry: margin=1in
numbersections: true
toc: yes
keep_tex: yes
---

 ```{r setup, include=F}
 knitr::opts_chunk$set(echo=F, error=F, message=F, warning=F, cache=T, results='asis', tidy=F)
 options(xtable.comment = FALSE)
```

\doublespacing

```{r child='intro/intro.Rmd'}
```

```{r child='theory/theory.Rmd'}
```

```{r child='survey_chapter/survey_chapter.Rmd'}
```

```{r child='entry_chapter/entry_chapter.Rmd'}
```

```{r child='appendix/appendix.Rmd'}
```

# References {-}
\markboth{REFERENCES}{}

\indent

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

\singlespacing

<!--chapter:end:dissertation.Rmd-->

