## Research Design

### The Afrobarometer Survey

To examine the relationship between repression and individual attitudes toward political participation and ethnic identities, I use waves 3-6^[The ethnic vs. national identity question was not asked in waves 1 and 2.] of the Afrobarometer survey. The Afrobarometer is administered by researchers at Michigan State University, the Institute for Democracy in South Africa, and the Center for Democratic Development in Ghana. In each wave the survey attempts to obtain a nationally-representative sample of 20-25 African countries. This is accomplished by randomly sampling geographic areas (villages, neighborhoods, etc), with selection probabilities weighted by population. Within each geographic area a starting point is chosen at random, from which interviews begin randomly selecting households. Individuals are then randomly selected within households, alternating between men and women to ensure gender balance. The sample in each country usually numbers either 1,200 or 2,400, depending on the size and diversity of the country. Respondents are asked over 300 questions on their demographics and background, and their opinions on a wide range of political and cultural questions. One advantage of using such a general survey is the relatively low likelihood that individuals will be primed to answer questions about ethnicity in a way that is not representative of their normal opinions [@Eifert2010].

Attributes for each survey wave are summarized in Table \@ref(tab:afro-topline). The four waves span the period 2005--2016, cover 38 countries, and collect a total of 158,362 individual responses. Response rates are generally quite high, averaging 76.5% in wave 6, and 77.7% in wave 5. A detailed summary of included countries is provided in Table \@ref(tab:response) of the Appendix.

Wave  | Years  | Total Responses  | Countries
--|---|---|--
 3 | 2005 | 25,397 | 18
 4 | 2008 | 27,713 | 20
 5 | 2011--2013 | 51,587 | 34
 6 | 2016 | 53,935 | 36
 Total | 2005--2016 | 158,362 | 36
 Table: (\#tab:afro-topline) The Afrobarometer Survey by Wave
 
The Afrobarometer is one of only a few surveys (the primary alternative being the World Values Survey) that provides a cross-national measure of ethnic identity. Given that the baseline salience of ethnicity varies greatly across countries, it is crucial that my theory be tested across a variety of contexts. But while the Afrobarometer facilitates such an analysis, it is not without its limitations. Cross-national comparability comes at the expense of studying country-specific nuances. Perhaps relatedly, the survey often does a poor job of defining abstract concepts, creating the possibility that respondents could interpret the same question in starkly different ways. The survey is conducted by a research assistant, creating the possibility of social desirability bias, as well as potential response biases resulting from the interviewer's ethnicity, gender, or other attributes. Finally, the prevalence of undemocratic regimes and other potential sources of repression in Africa create the possibility that individuals will not feel free to answer the questions honestly.

One more specific concern relevant to the present application is that in rare cases the Afrobarometer excludes geographic areas experiencing significant violence or other factors that would pose a danger to interviewers. Additionally, questions about ethnic identity are not asked in some countries where doing so is deemed to be potentially harmful to the sampled communities. It is impossible to estimate the direction or magnitude of the bias introduced by these decisions. The external validity of this analysis is therefore limited; I am unable to infer whether the patterns identified in the sample are likely to hold in the most violent and ethnically-polarized societies.

\singlespacing

\begin{longtable}{p{3cm} p{6cm} p{6cm}}
Variable & Question Text & Responses \\
\hline
Attitude Toward Violence & "During the past year, have you or anyone in your family: Been physically attacked?" & \begin{enumerate}
\item "No"
\item "Once"
\item "Twice"
\item "Three or More Times"
\item "Don't Know."
\end{enumerate} \\
\hline
Ethnic Identity & "Let us suppose that you had to choose between being a [ENTER NATIONALITY] and being a [Respondent’s Ethnic Group]. Which of the following best expresses your feelings?" & \begin{enumerate}
\item "I feel only [ethnicity]"
\item "I feel more [ethnicity] than [nationality]"
\item"I feel equally [ethnicity] and [nationality]"
\item "I feel more [nationality] than [ethnicity]"
\item "I feel only [nationality]"
\end{enumerate} \\
\hline
Political Participation & "Here is a list of actions that people sometimes take as citizens when they are dissatisfied with government performance. For each of these, please tell me whether you, personally, have done any of these things during the past year. If not, would you do this if you had the chance: Participated in a demonstration or protest march / Attended a community meeting / Used force or violence for a political cause." & \begin{enumerate}
\item "No, would never do this"
\item "No, but would do if had the chance"
\item "Yes, once or twice"
\item "Yes, several times"
\item "Yes, often."
\end{enumerate} \\
\hline
Voting & "Understanding that some people were unable to vote in the most recent national election in [20xx], which of the following statements is true for you?" & \begin{enumerate}
\item You were not registered to vote"
\item "You voted in the elections"
\item "You decided not to vote"
\item "You could not find the polling station"
\item"You were prevented from voting"
\item "You did not have time to vote"
\item "You did not vote because you could not find your name in the voters' register"
\item "Did not vote for some other reason"
\item "You were too young to vote"
\item "Don't Know/ Can't Remember"
\end{enumerate} \\
\hline
Intimidation & "During election campaigns in this country, how much do you personally fear becoming a victim of political intimidation or violence?" & \begin{enumerate}
\item "A lot" 
\item "Somewhat"
\item "A little bit" 
\item "Not at all" 
\item "Don’t know"
\end{enumerate} \\
\hline
\caption{Question Wording} \label{tab:wording}\\
\end{longtable}

\doublespacing

### Dependent Variables

#### Attitude Toward Violence {-}

The first dependent variable explored in this chapter is willingness to use violence. To distinguish factors that influence an individual's willingness to engage in violence from those that make them more active generally, I include several other forms of political behavior, including voting, attending community meetings, and protesting. The question wordings and possible responses are reported in Table \@ref(tab:wording). The violence, meeting, and protest questions share a common question stub. The voting question differs as individuals generally vote only once, and it solicits explanations for why individuals did not vote. I collapse each variable into binary categories with individuals who engaged in the activity at least once coded as one, and individuals who did not participate in the activity for any reason, including those who are willing but have not actually done the activity, coded as zero. Leaving the measure as a five-point scale and using does not substantially alter the results (see Table \@ref(tab:ordinal) in the Chapter 3 Appendix). 

Each of these measures is self-reported, and not subject to any independent verification. It is well established in the US context that self-reported surveys overestimate the prevalence of voting, introducing bias to models of political participation [@Bernstein2001]. It is unclear whether such effects are similarly prevalent in Africa. 70.4% of respondents in the full sample reported voting, though the number varies wildly across countries in a manner that generally matches variation in actual voter turnout [see @Kuenzi2007]. Social desirability bias may lead not only the voting figure, but participation rates for the other forms of political activity to be inflated. Alternatively, it is possible that not participating is the more socially-desirable position in some cases, particularly with regards to participation in violence. I therefore cannot rule out the possibility that any relationships between being attacked and political participation are the result of inaccurate self-reports on both measures.

Variable  | Yes  | No  | Percentage Yes
--|---|---|--
Violence | 1473  | 50077  | 2.9%
Protest |  16492 | 142056  | 10.4%
Meeting  | 92849  | 65719  | 58.6%
Vote | 111632 | 46952 | 70.4%
Table: (\#tab:partic) Summary of Participation (waves 3-6)

The participation measures are summarized in Table \@ref(tab:partic). Participation in violence is rare, with only 2.9% of respondents reporting to have done it at least once in the past year. Participation rates increase as the degree of commitment required decreases - 10.4% participated in at least one protest, 58.6% participated in a community meeting, and 70.4% voted.

#### Ethnic Identity {-}

The second dependent variable is ethnic identification. The Afrobarometer asks individuals about the extent to which they identify with their ethnic group, relative to their nation. Refer again to Table \@ref(tab:wording) for the question wording. I collapse the measure into a binary variable, with respondents who identify only with their ethnic group and more with their ethnic group than their nation coded as ethnic identifiers, and all others as non-ethnic identifiers. Using the raw five-point scale (ranging from ethnically-oriented to most nationalist) yields similar results when used in an ordered logit (see Table \@ref(tab:ordinal) in the Chapter 3 Appendix).

Individuals self-report their ethnicity earlier in the survey. The question is open-ended, allowing for the possibility that respondents may conceive of ethnicity in ways that do not comport with scholarly definitions. Indeed, around 1.5% of respondents provide answers such as "African" or the name of a sub-national region. The vast majority, however, choose ethnicities that appear in externally-imposed classifications, such as the Ethnic Power Relations data [@Vogt2015].

```{r ethnic}
library(xtable)
library(sjmisc)
load("/Users/david/Dropbox/Dissertation/Document/survey_chapter/survey_data/merged_afrobarometer.Rds") #built by afrobarometer_dataprep.R
options(xtable.comment = FALSE)
tab <- table(to_label(afro$eth_id))
tab2 <- cbind(tab, prop.table(tab)*100)
colnames(tab2) <- c("Count", "Percentage")
xtable(tab2, digits=c(0,0,1), caption="Summary of Ethnic Identification (waves 3-6)", label="tab:ethnic")
```

Relatively few respondents identify with their ethnic group, with 4.3% answering that they feel only an ethnic identity, and 7.4% saying that their ethnic identity was more prevalent than their national identity (see Table \@ref(tab:ethnic)). A plurality of respondents (35.8%) said that they felt equally attached to their national and ethnic identities, and a large percentage (34.1%) said that they feel only a national identity.

### Independent Variables

*H1* predicts that individuals who experience violent repression should be more likely to participate in violence than others, and *H2* predicts that repression should increase the extent that individuals identify with their ethnic group. I test these propositions using both individual-level and national-level measures of repression. At the individual level, I use an Afrobarometer question that asks respondents whether they or a family member has been attacked in the past year (see Table \@ref(tab:wording) for question text).  I recode the variable into a binary measure with individuals who experienced any attacks coded as 1, and individuals who experienced no attacks coded as 0. This question has two noteworthy limitations. First, it does not differentiate between individuals who were personally attacked from family members of people who were attacked. However, I expect that this feature is more likely to introduce bias against my hypotheses, than in their favor. The effect of violence on family members of people who are attacked should be less than or equal to that on people who personally experience violence. If this assumption holds, including family members should either have no effect or understate the effect of being attacked. Second, the question does not identify the source of the attack. While government repression may account for some attacks, the measure likely also includes violence from non-state actors including rebel groups, as well as common criminal activity. Again, however, I expect that any potential bias is more likely to work against my hypotheses than in the same direction. Attacks that clearly should not be characterized as repression, such as domestic violence, should be less likely to influence willingness to engage and violence or identify with an ethnic group. Thus, including these types of attacks in the measure is more likely to understate the effect of repression than overstate it. With these coding decisions, 10.4% of respondents report having experienced an attack.

I also include a measure of intimidation, as I expect that the *belief* that the risk of non-violence is approaching that of violence should be sufficient to alter an individual's attitudes. While the question is somewhat limited in scope (see Table \@ref(tab:wording)), only asking about election-related violence, this does bring the advantage of shedding light on the reason why an individual might be targeted. 28.6% of respondents reported at least some fear of being attacked during an election.

An individual may not need to experience violence personally to update their calculations about their probability of experiencing it in the future. For example, if an ethnic minority in one part of a country is repressed, members of other minority groups may increase their expectation of being repressed themselves. Thus, I include a national-level measure of repression, the Latent Human Protection Scores, version 2 [@Fariss2014; @Schnakenberg2014]. The project uses a Bayesian measurement model to estimate latent human rights scores using several data sources including US State Department and Amnesty International country reports, and several scholarly datasets on repression and mass killing. This data improves on previous approaches to measuring human rights by accounting for the fact that the standards by which government and NGO reports have judged countries have generally improved both over time and cross-nationally. The result is an aggregate measure that ranges from roughly -3 (most repressive) to 3 (most respectful of human rights). The score is calculated yearly, 1946--2015 for each country. I match the Latent Protection Human Protection Scores to each Afrobarometer respondent by the respondent's country and the year in which the survey was conducted. Within the sample, the measure ranges from -2.18 (Sudan in 2013) to 1.81 (Botswana in 2012), with mean of 0.26.^[Calculated with all country-years included in the data weighted equally.] The sample thus lacks any cases with the exceptionally levels of respect for human rights, as would be seen in many European democracies. The average, however, is quite close to the full sample mean of 0.29.

### Control Variables

I draw on previous studies of participation in rebellion [e.g. @Humphreys2008] and ethnic identity [e.g. @Eifert2010; @Gibler2012; @Masella2013; @Robinson2014] to identify a set of relevant control variables. Each of these measures comes from the Afrobarometer, though some are not included in all waves. First, I include the respondent's gender, as men are substantially more likely to participate in violence than women. Next I include age and an ordinal measure of educational attainment as both have been shown to be negatively related to the probability of participation in violence. Additionally, I include binary indicators of whether the respondent is employed at least part-time, as unemployed individuals are more likely to rebel, whether they reside in an urban area, as urban-dwellers have been shown to rebel at higher rates, and whether they support the ruling party, as these individuals would obviously be less likely to take political action against the government. I have examined several other controls, but exclude them from the models reported here as they are neither statistically significant nor do they alter the performance of my variables of interest. These include a binary indicator for individuals who work in agriculture (farming and fishing), an index of the level of economic development in the respondent's community, and the size of the respondent's ethnic group.

At the country level I control for a curvilinear effect for ethnolinguistic fractionalization, using data from @fearonlaitin03. The intuition behind this choice is that at very low levels of fractionalization, meaning most individuals belong to the same ethnic group, ethnicity is not likely to be an important social cleavage. The same is likely to hold at the opposite extreme, where individuals might fragmented into a sufficiently large number of groups that ethnicity is unlikely to be a salient. A curvilinear effect should thus identify the cases in the middle of the spectrum where ethnicity is likely to matter. Additionally, I include the country's Polity IV regime score [@Marshall2016], as @Eifert2010 find that elections can induce greater levels of ethnic identification. Finally, as forms of violence besides repression might influence I include indicators of whether the country had a separatist war or civil war over the central government during the year the respondent was interviewed, constructed from the Uppsala Conflict Data [@Melander2016].

At the country level I control for a curvilinear effect for ethnolinguistic fractionalization, using data from @fearonlaitin03. The intuition behind this choice is that at very low levels of fractionalization, meaning most individuals belong to the same ethnic group, ethnicity is not likely to be an important social cleavage. The same is likely to hold at the opposite extreme, where individuals might fragmented into a sufficiently large number of groups that ethnicity is unlikely to be a salient. A curvilinear effect should thus identify the cases in the middle of the spectrum where ethnicity is likely to matter. The fractionalization measure does have limitations. Notably, it assumes individuals have a single, stable ethnic identity, whereas recent research suggests identity can vary across contexts and time [@Chandra2009a]. Furthermore, the measure is extrapolated from a single underlying measurement from 1964, and may be subject to some measurement error, particularly in later years. The strength of the fractionalization measure relative to alternatives lies in its ability to capture to some extent the magnitude of differences between ethnic groups, as it is interpretable as the probability that two randomly selected individuals will be able to communicate. Thus, closely-related ethnic groups that are able to communicate do not contribute to fractionalization, whereas more stark differences do.

Additionally, I include the country's Polity IV regime score [@Marshall2016], as @Eifert2010 find that elections can induce greater levels of ethnic identification. Finally, as forms of violence besides repression might influence I include indicators of whether the country had a separatist war or civil war over the central government during the year the respondent was interviewed, constructed from the Uppsala Conflict Data [@Melander2016].

### The Model

As I am interested in the effects of variables measured at both the individual and country levels, and my dependent variables are all binary, a multilevel logistic regression model is the appropriate method of analysis. I begin with a relatively simple model with random intercepts for each country. The intuition behind this model is that the baseline values for each dependent variable vary by country, while the independent variables have a consistent effect in each country. For example, the baseline probability of ethnic identification might vary from country to country, but the model assumes that the effect of repression will be the same across all countries. For robustness, I estimate more complex models with random intercepts for each ethnic group nested within each country, and with random intercepts for each survey wave. Additionally, I utilize the survey weights provided by Afrobarometer, meaning that individuals from under-sampled groups are weighted more heavily in the regressions.

Individual-level variables are interpreted normally, with coefficients representing the increase in the logged odds ratio of the dependent variable associated with a one-unit increase in the independent variable. The country-level variables are used in a separate model, estimated simultaneously, in which the dependent variable is the group-level intercept. Thus, country-level coefficients predict the change in baseline probability in a country associated with a one-unit increase in the independent variable.
